spring:
  jpa:
    generate-dll: true
  datasource:
    url: jdbc:postgresql://localhost:5433/user_db
    username: postgres
    password: postgres
    hikari:
      schema: user_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS user_schema
      connection-timeout: 10000

app:
  security:
    type: db