version: '3.8'

services:
  socket-server:
    image: socket-server
    ports:
      - "8888:8888"

  socket-client:
    image: socket-client
    environment:
      - SOCKET_SERVER_HOST=socket-server
    depends_on:
      - socket-server
